Papers from master thesis and FRIA proposal Ilyes Gharbi
demiurge-project/demiurge-bib pull request #50
Opened 2022-09-06 12:36 UTC by ilgha

2022-09-06 12:54 UTC, KenN7 commented on bibliography.bib
> +@Book {HasLigFraBir2019book,
this is duplicated
https://github.com/demiurge-project/demiurge-bib/blob/5c51777aae7c3ef2292759a85850f7395276e218/bibliography.bib#L260

2022-09-06 12:56 UTC, KenN7 commented on bibliography.bib
> +@Article{HeaDumOsuPlaSch1998IEEEISA,
duplicated see below

2022-09-06 12:56 UTC, KenN7 commented on bibliography.bib
> +@ARTICLE{HeaDumOsu-etal1998IEEEISA,
This is duplicated at line 7163

2022-09-06 12:57 UTC, KenN7 commented on bibliography.bib
> +@inproceedings{AkrSchSeb2012ecmlpkdd,
duplicated line 7177

2022-09-06 12:57 UTC, KenN7 commented on bibliography.bib
> +    title        = {Preference-based policy learning},
duplicated line 7192

2022-09-06 12:58 UTC, KenN7 commented on bibliography.bib
> +    title        = {Algorithms for inverse reinforcement learning},
duplicated line 7206

and a lot of the following also

2022-09-06 12:58 UTC, KenN7 commented on bibliography.bib
> +@InProceedings {busoniu2006decentralized,
the key is bad

2022-09-06 13:00 UTC, KenN7 commented on bibliography.bib
> +    journal      = IJRR,
journals the identifier should be capitalized (e.g. SI),

2022-09-06 13:00 UTC, KenN7 commented on bibliography.bib
> +@Article{OsaPajNeu-etal2018ftr,
journals the identifier should be capitalized (e.g. SI),

2022-09-06 13:01 UTC, KenN7 commented on bibliography.bib
> +    journal      = {arXiv preprint arXiv:1602.05450},
remove doi

2022-09-06 13:01 UTC, KenN7 commented on bibliography.bib
> +@Article{BahGupPat2022arxiv,
see https://github.com/demiurge-project/demiurge-bib/blob/5c51777aae7c3ef2292759a85850f7395276e218/bibliography.bib#L2822

for arxiv papers

2022-09-06 13:02 UTC, KenN7 commented on journal.bib
> +@string{ HX          = "HardwareX" }
already present 3 lines below...

2022-09-06 13:02 UTC, KenN7 commented on journal.bib
> +@string{ FRAI        = "Frontiers in Robotics and AI" }
duplicated 3 lines below

2022-09-06 13:07 UTC, KenN7 commented
Most of the keys for journals are wrong, also check the bib commands like "@InProceedings" most of them are not capitalised.
Half of the papers  appear twice

2022-09-06 15:59 UTC, ilgha commented
Thank you @KenN7 for your comments!

2022-09-08 06:46 UTC, KenN7 commented
Another advice: idk how familiar you are with git, but it would be great if the commit history was clean.
I mean, having commits that add and then remove the same things only add confusion to the repo's history.
you should lookup "git rebase" in order to rewrite your history and only leave one commit there.
If you rebase the history on your repo, your PR should normally be updated .

2022-09-12 12:09 UTC, glegarda commented on author.bib
> +@string{ Abbeel_P             = "Abbeel, Pieter" }
Should appear before Abdullah_S

2022-09-12 13:26 UTC, glegarda reviewed
There are quite a few errors, including duplicate entries, improper capitalisation and ordering, and even mismatches between author names and their corresponding keys. Before this PR is accepted (and also for the next time), please go over all the changes carefully.

2022-09-12 13:26 UTC, glegarda commented on journal.bib
> +@string{ IMASA       = "Innovations in multi-agent systems and applications-1" }
```suggestion
@string{ IMASA       = "Innovations in Multi-Agent Systems and Applications -- 1" }
```

2022-09-12 13:26 UTC, glegarda commented on journal.bib
> +@string{ MICPRO      = "Microprocessors and Microsystems - Embedded Hardware Design" }
Duplicate (see 5 lines below)

2022-09-12 13:26 UTC, glegarda commented on journal.bib
> +@string{ NATUBIOT    = "Nature biotechnology" }
```suggestion
@string{ NATUBIOT    = "Nature Biotechnology" }
```

2022-09-12 13:26 UTC, glegarda commented on journal.bib
> +@string{ ML          = "Machine Learning" }
Should go before MACH

2022-09-12 13:26 UTC, glegarda commented on journal.bib
> +@string{ PACMPL      = "Proceedings of the ACM on Programming Languages" }
Duplicate (see 6 lines below)

2022-09-12 13:26 UTC, glegarda commented on journal.bib
> +@string{ RMP         = "Reviews of Modern Physics" }
Duplicate (see 3 lines above)

2022-09-12 13:26 UTC, glegarda commented on publisher.bib
> +@string{ pub_El        = "Elsevier" }
```suggestion
@string{ pub_EL        = "Elsevier" }
```

2022-09-12 13:26 UTC, glegarda commented on proceedings.bib
> +@string{ aaai_2021      = "AAAI'21: Proceedings of the 36st national conference on Artificial intelligence" }
```suggestion
@string{ aaai_2021      = "AAAI'21: Proceedings of the 36th national conference on Artificial intelligence" }
```

2022-09-12 13:26 UTC, glegarda commented on proceedings.bib
> +@string{ corl_2017      = "2017 Conference on robot learning" }
```suggestion
@string{ corl_2017      = "2017 Conference on Robot Learning" }
```

2022-09-12 13:26 UTC, glegarda commented on proceedings.bib
> +@string{ ecmlpkdd_2011  = "2011 Joint European conference on machine learning and knowledge discovery in databases" }
```suggestion
@string{ ecmlpkdd_2011  = "2011 Joint European Conference on Machine Learning and Knowledge Discovery in Databases" }
```

2022-09-12 13:26 UTC, glegarda commented on proceedings.bib
> +@string{ ecmlpkdd_2012  = "2012 Joint European conference on machine learning and knowledge discovery in databases" }
```suggestion
@string{ ecmlpkdd_2012  = "2012 Joint European Conference on Machine Learning and Knowledge Discovery in Databases" }
```

2022-09-12 13:26 UTC, glegarda commented on proceedings.bib
> +@string{ icml_2004      = "ICML '04: Proceedings of the twenty-first international conference on Machine learning" }
```suggestion
@string{ icml_2004      = "ICML '04: Proceedings of the Twenty-first International Conference on Machine Learning" }
```

2022-09-12 13:26 UTC, glegarda commented on proceedings.bib
> +@string{ irc_2018       = "2018 second IEEE international conference on robotic computing (IRC)" }
```suggestion
@string{ irc_2018       = "2018 second IEEE International Conference on Robotic Computing (IRC)" }
```

2022-09-12 13:31 UTC, glegarda commented
Also, please add the corresponding entries to all "-short.bib" files.

2022-09-13 11:55 UTC, ilgha commented on author.bib
> +@string{ Hsu_D                = "Hsu, Daniel" }
It is still in the wrong place

2022-09-13 11:55 UTC, ilgha commented on author.bib
> +@string{ Lopes_AM              = "Lopez, Antonio M." }
Lopez_AM*

2022-09-13 19:53 UTC, jonaskuResearch requested changes
Please check publisher and address for all added entries in the bibliography.

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing publisher and address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing publisher and address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-09-13 19:53 UTC, jonaskuResearch commented on bibliography.bib
> +    address      = {},
Missing address

2022-10-04 14:52 UTC, closed without merging